In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('movie-review.csv')
df

,title,review,sentimentScore
0,Monsoon Wedding,MONSOON WEDDING is a wonderful film in which m...,POSITIVE
1,Monsoon Wedding,A celebration of life that acknowledges how fa...,POSITIVE
2,Monsoon Wedding,Not content to merely direct traffic of inters...,POSITIVE
3,Monsoon Wedding,... among the most universal of films,POSITIVE
4,Monsoon Wedding,"A big, galloping party movie in which the part...",POSITIVE
...,...,...,...
276921,The Invisible Circus,When flashbacks tease us with bits of informat...,NEGATIVE
276922,The Invisible Circus,Watching it is like having a book read to you ...,NEGATIVE
276923,The Invisible Circus,"An absorbing story about hope, youthful ardenc...",POSITIVE
276924,The Invisible Circus,"Brewster has us caught up in her adventure, ma...",POSITIVE
276925,The Invisible Circus,"There's painfully little that's enlightening, ...",NEGATIVE

In [9]:
df = df.dropna()
df

,title,review,sentimentScore
0,Monsoon Wedding,MONSOON WEDDING is a wonderful film in which m...,POSITIVE
1,Monsoon Wedding,A celebration of life that acknowledges how fa...,POSITIVE
2,Monsoon Wedding,Not content to merely direct traffic of inters...,POSITIVE
3,Monsoon Wedding,... among the most universal of films,POSITIVE
4,Monsoon Wedding,"A big, galloping party movie in which the part...",POSITIVE
...,...,...,...
276921,The Invisible Circus,When flashbacks tease us with bits of informat...,NEGATIVE
276922,The Invisible Circus,Watching it is like having a book read to you ...,NEGATIVE
276923,The Invisible Circus,"An absorbing story about hope, youthful ardenc...",POSITIVE
276924,The Invisible Circus,"Brewster has us caught up in her adventure, ma...",POSITIVE
276925,The Invisible Circus,"There's painfully little that's enlightening, ...",NEGATIVE

In [10]:
df = df.drop_duplicates()
df

,title,review,sentimentScore
0,Monsoon Wedding,MONSOON WEDDING is a wonderful film in which m...,POSITIVE
1,Monsoon Wedding,A celebration of life that acknowledges how fa...,POSITIVE
2,Monsoon Wedding,Not content to merely direct traffic of inters...,POSITIVE
3,Monsoon Wedding,... among the most universal of films,POSITIVE
4,Monsoon Wedding,"A big, galloping party movie in which the part...",POSITIVE
...,...,...,...
276921,The Invisible Circus,When flashbacks tease us with bits of informat...,NEGATIVE
276922,The Invisible Circus,Watching it is like having a book read to you ...,NEGATIVE
276923,The Invisible Circus,"An absorbing story about hope, youthful ardenc...",POSITIVE
276924,The Invisible Circus,"Brewster has us caught up in her adventure, ma...",POSITIVE
276925,The Invisible Circus,"There's painfully little that's enlightening, ...",NEGATIVE

In [11]:
df.to_csv('movie-review-cleaned.csv', index=False)